services:
  seodesk.api:
    build:
      context: .
      dockerfile: src/SEODesk.API/Dockerfile
    container_name: seodesk-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_HTTP_PORTS=5000
      - DATABASE_URL=postgresql://postgres:YenmNauAjfRmywgzFdhrWzVegazsIjRG@hopper.proxy.rlwy.net:22302/railway
    ports:
      - "5000:5000"
    networks:
      - seodesk-network
    restart: unless-stopped
    volumes:
      - dataprotection-keys:/persistent-keys

networks:
  seodesk-network:
    driver: bridge

volumes:
  dataprotection-keys:
    driver: local
